### ISSUE TITLE
Copy Center Sprint 2 - Woo Commerce Customer Workflow

### ISSUE THREAD

**Issue by jpham93** [vta/microsites#13]
|# Copy Center 2.0 Sprint 2 - https://projects.vta.org/versions/21

The following issue covers multiple work tickets that are defined in **Sprint 2** of the Copy Center Project in _Open Project_. A few things have been accomplished already via WordPress's admin panel. Since each work ticket is a relatively small task, they will each represent a **TODO** in this issue.

### Requirements:
- [x] ~[|#311 Work Ticket Queue](https://projects.vta.org/projects/copy-center/work_packages/311)~ _(WooCommerce built-in feature)_
- [x] ~[|#315 Order numbers](https://projects.vta.org/projects/copy-center/work_packages/315)~ –_(WooCommerce built-in feature)_
- [x] [|#316 Copy Center ETA](https://projects.vta.org/projects/copy-center/work_packages/316) – Give a standard 72-hour window as a default notification. Allow this notification to be updated when ETA changes.
- [x] [|#317 Queue Order](https://projects.vta.org/projects/copy-center/work_packages/318)  –_(WooCommerce built-in feature)_
- [x] [|#318 Ready to Pickup Email](https://projects.vta.org/projects/copy-center/work_packages/318) – An email that notifies "Ready to pick up" as well as the cost related to the order. (We may want to implement the cost information in a later sprint)
- [x] ~[|#319 Reorder/ Order History](https://projects.vta.org/projects/copy-center/work_packages/319)~ – _(WooCommerce built-in feature)_
- [x] [|#322 Order Status](https://projects.vta.org/projects/copy-center/work_packages/322) – _(WooCommerce built-in feature)_ **Will need additional PHP code to create custom status + emails**. For custom Order Status email notifications, please refer to this repository: [WooCommerce Custom Emails](https://github.com/jpham93/wc-custom-emails)
- [x] ~[|#302 User Registration](https://projects.vta.org/projects/copy-center/work_packages/302) – After the user signs up, a confirmation email should be sent with an activation link.~ _Resolved with Post SMTP plugin and configuration on GF_

**Comment by jpham93** [comment]
Closes #14
